### ISSUE TITLE
$home-office

### ISSUE THREAD

**Issue by zowber** [alphagov/govuk_frontend_toolkit#253]
I'm trying to understand where the departmental brand colour variable $home-office has come from? Is this repo the canonical source for colour values?

My concern is that in colours.scss it's #9325b2. Yet on the page referenced in a comment at the top of that scss file (http://alphagov.github.io/design/gov.uk.colours/) it's #804292. And in a Home office brand guidelines document I have it has been captured as Pantone 2592C/#8f23b3.

**Comment by JenAllum** [comment]
Hello, 

You're right, there is some confusion here and there isn't even a clear reason why the two colours are different on live. 

Having spoken to Mark Hurrell, head of design at GOV.UK, he agrees that we should standardise. We could do this in two ways. If you want to raise a PR we can review and merge, or we (the Core product team) would need to schedule this work in for the future, though it's unlikely to be prioritised in the short term due to other work pressures at the moment (unfortunately). 

Are you looking to change the colour, or is it that you need to use the colour elsewhere and you're not sure which colour to use? 

Our main priority in any change would be to ensure the colour is accessible. 

Thanks, 
Jen

**Comment by dsingleton** [comment]
> My concern is that in colours.scss it's #9325b2. Yet on the page referenced in a comment at the top of that scss file (http://alphagov.github.io/design/gov.uk.colours/) it's #804292. And in a Home office brand guidelines document I have it has been captured as Pantone 2592C/#8f23b3.

Just to clarify the page referenced in that comment, that is super out of date. Thanks for highlighting it, we've [updated this repo](https://github.com/alphagov/govuk_frontend_toolkit/pull/256) not to reference it anymore, and we've removed the old page too.

`colours.scss` in this repo should be authoritative definition, and as Jen mentioned if thats incorrect then it should get updated.

**Comment by zowber** [comment]
I'm essentially just looking for the definitive value for the Home Office primary brand colour.

I expect the document I've seen which suggested the colour value should be Pantone 2592C/#8f23b3 is simply out-of-date. I'm happy to accept the value in `colours.scss` given @dsingleton's comment about this repo being the authoritative source.

Thanks for looking at the issue.

**Comment by fofr** [comment]
Looks like this has been resolved, so I'm closing the issue.
