### ISSUE TITLE
Tracking end-to-end test

### ISSUE THREAD

**Issue by alecgibson** [alphagov/govuk_frontend_toolkit#363]
It would be good to have a full end-to-end integration test of Google Analytics click tracking (which lives in "Static")

We currently have unit tests that cover:
* Tracking attributes are rendered by Ruby
* JS tracking event is fired from a tracked element

However, there's a disconnect in that nothing checks that the Ruby-rendered tracking events have the correct module name (ie Ruby renders an element, and clicking on _that_ element fires a tracking event).

For more context, see: https://github.com/alphagov/static/pull/875

**Comment by 36degrees** [comment]
I believe this issue is specific to GOV.UK (Publishing) as Frontend Toolkit doesn't really have a concept of 'end-to-end'.

Either way, following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Frontend Toolkit will now only get major bug fixes and security patches, so I'm going to close this.
