### ISSUE TITLE
Issue using Frontend Toolkit after updating to jQuery 3.x

### ISSUE THREAD

**Issue by eserkansozer** [alphagov/govuk_frontend_toolkit#443]
When I upgraded to jQuery version 3, I started to get the following error in stop-scrolling-at-footer.js:

jquery.min.js:2 Uncaught TypeError: e.indexOf is not a function
    at w.fn.init.w.fn.load (jquery.min.js:2)
    at stop-scrolling-at-footer.js:136
    at stop-scrolling-at-footer.js:138

Previous versions of jQuery did not cause this.

**Comment by nickcolley** [comment]
Hello @eserkansozer !

We currently only have code that supports version jQuery 2.x.

jQuery version 3.x+ is a breaking release so the current code is very likely to not work with it this version.

We have not updated to jQuery 3.x since it does not cover the browsers / devices as listed in the Service Manual (https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices#browsers-to-test-in)

I'm going to share this with the GDS Frontend Community and also the GOV.UK Design System (who owns this 'product' at GDS), and we'll figure out the best way to move forwards.

For more info about this vulnerability see https://snyk.io/vuln/npm:jquery:20150627

**Comment by frankieroberto** [comment]
Now might be a good time to start removing the jQuery dependency instead?

**Comment by 36degrees** [comment]
I am concerned we're going to go off on a bit of a tangent here that is not helpful to resolving the original issue. Can we start another issue if we want to discuss removing jQuery as a dependency?

@eserkansozer I think @nickcolley mostly covered it, but upgrading to jQuery 3 will cause issues for users of your service using older browsers. Assuming you're trying to upgrade in response to CVE-2015-9251, I would suggest instead remaining on jQuery 1.x and ensuring that any AJAX requests you are making specify `dataType`, which as I understand it effectively mitigates the issue.

**Comment by eserkansozer** [comment]
Thank you @nickcolley @36degrees . We don't have any cross-domain Ajax requests in our service right now therefore we are safe. 

The initiation of this discussion was GitHub sending us a warning notification about the vulnerability (which is still valid as anybody may misuse jQuery 1.x Ajax functions in our service or others which include front-end-toolkit as package). Though the risk may be regarded as low and not GDS's responsibility IMHO.

I understand that GDS needs to support older browsers so upgrade is not possible.

**Comment by 36degrees** [comment]
That all makes sense – are you happy for me to close this issue as resolved?

**Comment by eserkansozer** [comment]
Yes, thank you.

Serkan Sozer


-------- Original message --------
